# DO NOT EDIT — this file is generated from cm.yaml and will be overwritten.
# To make changes, edit cm.yaml and run: cm update
# Generated by container-magic: https://github.com/markhedleyjones/container-magic

################################################################################
# Stage: base
################################################################################
FROM python:3.12-slim AS base

ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=nonroot \
    USER_HOME=/home/nonroot \
    WORKSPACE_NAME=workspace
ENV WORKSPACE=${USER_HOME}/${WORKSPACE_NAME}
WORKDIR ${USER_HOME}
# Create user account (handles renaming if UID exists with different name)
# hadolint ignore=DL4006
RUN if [ "${USER_NAME}" != "root" ]; then \
        EXISTING_USER=$(getent passwd "${USER_UID}" | cut -d: -f1); \
        if [ "${EXISTING_USER}" = "${USER_NAME}" ]; then \
            echo "User ${USER_NAME} with UID ${USER_UID} already exists, skipping creation"; \
        elif [ -n "${EXISTING_USER}" ]; then \
            echo "Renaming user ${EXISTING_USER} to ${USER_NAME}"; \
            usermod -l "${USER_NAME}" "${EXISTING_USER}" && \
            usermod -d "${USER_HOME}" -m "${USER_NAME}" || true; \
        else \
            getent group "${USER_GID}" >/dev/null 2>&1 || \
                groupadd --gid "${USER_GID}" "${USER_NAME}"; \
            useradd --uid "${USER_UID}" --gid "${USER_GID}" --home-dir "${USER_HOME}" --create-home "${USER_NAME}"; \
        fi && \
        chown "${USER_UID}:${USER_GID}" "${USER_HOME}"; \
    fi
# Disable PEP 668 (externally-managed-environment): host-system protection
# against apt/pip conflicts, not applicable inside containers where the whole
# environment is disposable.
RUN rm -f /usr/lib/python*/EXTERNALLY-MANAGED \
          /usr/local/lib/python*/EXTERNALLY-MANAGED \
          /opt/conda/lib/python*/EXTERNALLY-MANAGED
RUN pip install --no-cache-dir \
        anthropic==0.116.0 \
        click==8.4.2 \
        pydantic==2.13.4 \
        pyyaml==6.0.3
# Pre-compile .pyc bytecode so imports don't pay the compile cost on every
# startup; the runtime user can't write .pyc back to root-owned site-packages.
# hadolint ignore=SC2046
RUN python3 -m compileall -q -j 0 $(python3 -c "import site; print(' '.join(site.getsitepackages()))")

################################################################################
# Stage: development
################################################################################
FROM base AS development

ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=nonroot \
    USER_HOME=/home/nonroot
ENV PYTHONPATH="/opt/anomalica-common"
RUN pip install --no-cache-dir pytest==9.1.1
# Pre-compile .pyc bytecode so imports don't pay the compile cost on every
# startup; the runtime user can't write .pyc back to root-owned site-packages.
# hadolint ignore=SC2046
RUN python3 -m compileall -q -j 0 $(python3 -c "import site; print(' '.join(site.getsitepackages()))")
USER ${USER_NAME}

################################################################################
# Stage: production
################################################################################
FROM base AS production

ARG USER_GID=1000 \
    USER_UID=1000 \
    USER_NAME=nonroot \
    USER_HOME=/home/nonroot
COPY workspace ${WORKSPACE}
USER ${USER_NAME}
